[package]
name = "jp-lexer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chumsky = "*"
mora = { package = "jp-mora", path = "../jp-mora" }
kanji = { package = "jp-kanji", path = "../jp-kanji" }
